#!/bin/bash

# Verification script that re-runs the Kerberos flow three times
# against previously captured correct test vectors.
#
# - Compiles all components except ca.c.
# - For each n in 1..3:
#   - Restores all *.txt inputs from TestVectors/Correct_*_n.txt.
#   - Runs the full flow (without ./ca).
#   - Compares every generated *.txt file against its corresponding
#     Correct_*_n.txt test vector.
# - If all three runs pass, logs success and deletes all *.txt files
#   generated by the C programs in the base directory, while keeping
#   the original test vectors under TestVectors/.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "${SCRIPT_DIR}"

echo "[0] Compiling Kerberos components (without CA)..."
gcc -Wall -o client client.c -lcrypto
gcc -Wall -o kdc kdc.c -lcrypto
gcc -Wall -o tgs tgs.c -lcrypto
gcc -Wall -o service service.c -lcrypto

# Compare all generated *.txt files against the Correct_*_n.txt
# vectors for the current run. Skips Client_Signature.txt because
# the client regenerates it each run.
compare_outputs_for_run() {
	local n="$1"
	local ok_var_name="$2"  # name of variable to mark run-level status
	local tv
	local fname base gen

	for tv in "${TV_FILES[@]}"; do
		fname="${tv##*/Correct_}"
		base="${fname%_"${n}".txt}"
		# Skip Client_Signature.txt because the client regenerates it each run
		if [ "${base}" = "Client_Signature" ]; then
			continue
		fi
		gen="${base}.txt"
		if [ ! -f "${gen}" ]; then
			echo "[ERROR] Run ${n}: missing generated file ${gen} (expected from ${tv})"
			eval "${ok_var_name}=false"
			all_ok=false
			continue
		fi
		if ! cmp -s "${tv}" "${gen}"; then
			echo "[ERROR] Run ${n}: mismatch for ${gen} compared to ${tv}"
			eval "${ok_var_name}=false"
			all_ok=false
		fi
	done
}

all_ok=true

for n in 1 2 3; do
	echo "[${n}.1] Preparing inputs from test vectors (run ${n})..."

	shopt -s nullglob
	TV_FILES=("${SCRIPT_DIR}"/Correct_*_"${n}".txt)
	shopt -u nullglob

	if [ ${#TV_FILES[@]} -eq 0 ]; then
		echo "[!] No test vectors found for run ${n} in ${SCRIPT_DIR}"
		all_ok=false
		continue
	fi

	# Remove any existing txt artifacts generated by the C programs,
	# but keep the Correct_* test vectors.
	for f in *.txt; do
		if [[ "$f" != Correct_* ]]; then
			rm -f "$f"
		fi
	done

	# Restore all *.txt inputs for this run from the test vectors.
	for tv in "${TV_FILES[@]}"; do
		fname="${tv##*/Correct_}"
		base="${fname%_"${n}".txt}"
		cp "${tv}" "${base}.txt"
	done

	run_ok=true

	echo "[${n}.2] Running client (AS_REQ phase)..."
	./client Client_temp_SK.txt Client_temp_PK.txt AS_temp_PK.txt
	echo "[${n}.2b] Verifying outputs after client (AS_REQ)..."
	compare_outputs_for_run "$n" run_ok

	echo "[${n}.3] Running KDC (AS_REP phase)..."
	./kdc Client_Signature.txt Client_temp_PK.txt AS_temp_SK.txt AS_temp_PK.txt
	echo "[${n}.3b] Verifying outputs after KDC (AS_REP)..."
	compare_outputs_for_run "$n" run_ok

	echo "[${n}.4] Running client again (TGS_REQ phase)..."
	./client Client_temp_SK.txt Client_temp_PK.txt AS_temp_PK.txt
	echo "[${n}.4b] Verifying outputs after client (TGS_REQ)..."
	compare_outputs_for_run "$n" run_ok

	echo "[${n}.5] Running TGS (TGS_REP phase)..."
	./tgs TGS_REQ.txt Key_AS_TGS.txt Key_Client_TGS.txt Key_Client_App.txt Key_TGS_App.txt
	echo "[${n}.5b] Verifying outputs after TGS (TGS_REP)..."
	compare_outputs_for_run "$n" run_ok

	echo "[${n}.6] Running client again (APP_REQ phase)..."
	./client Client_temp_SK.txt Client_temp_PK.txt AS_temp_PK.txt
	echo "[${n}.6b] Verifying outputs after client (APP_REQ)..."
	compare_outputs_for_run "$n" run_ok

	echo "[${n}.7] Running service (APP_REP phase)..."
	./service APP_REQ.txt Key_TGS_App.txt
	echo "[${n}.7b] Verifying outputs after service (APP_REP)..."
	compare_outputs_for_run "$n" run_ok

	if ${run_ok}; then
		echo "Run ${n} verification passed."
	else
		echo "Run ${n} verification FAILED."
	fi

done

if ${all_ok}; then
	echo "All 3 verification runs passed. Cleaning generated files (*.txt except Correct_*)..."
	for f in *.txt; do
		if [[ "$f" != Correct_* ]]; then
			rm -f "$f"
		fi
	done
	echo "Verification completed successfully. Test vectors remain under ${SCRIPT_DIR}."
	exit 0
else
	echo "One or more verification runs failed. Generated files have been kept for inspection."
	exit 1
fi
